<?php
    $form = $this->form;
    
    $form->setAttribute(
        'action',
        $this->url('livraria-admin', array(
            'controller' => 'categorias',
            'action' => 'new'
        ))
    );
    
    $form->prepare();    
?>
<div class="row">
    <div class="col-lg-12">
        <h3>Nova Categoria</h3><br />
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('id')); ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('nome')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>        
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>



